name : Train Boston model and upload artifact

on:
  push:
    branches: 
      - deployment

jobs:
  train-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Train and Eval
        run: | 
          mkdir -p artifacts/
          python train.py

      - name: Upload the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: models
          path: artifacts/
  

  deploy-artifacts:
    runs-on: ubuntu-latest
    needs: train-and-upload
    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: models
          path: artifacts/

      - name: Inference
        run: python inference.py
